### ISSUE TITLE
[Optimization] `MsgSharesUsed` requires remainder operation

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#11]
`MsgSharesUsed` uses remainder operation (i.e., `%`) to "increment the share count if the message overflows the last counted share". As an alternative, the following would probably be faster:
```
shareCount := 1 + ((msgSize - 1) / appconsts.SparseShareContentSize);
```
Source: https://stackoverflow.com/questions/2745074/fast-ceiling-of-an-integer-division-in-c-c

**Comment by rootulp** [comment]
Closed by this unmerged PR https://github.com/celestiaorg/celestia-app/pull/1084#issue-1468930816
