### ISSUE TITLE
Unit length missing from estimating `txBytes` in `rawShareCount`

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#13]
When estimating the number of shares (see https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/app/estimate_square_size.go#L145), each TXs should have the unit length added (similarly to evidence, see https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/app/estimate_square_size.go#L194).

**Comment by mpoke** [comment]
This is also the case for malleated tx, i.e., https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/app/estimate_square_size.go#L173

**Comment by rootulp** [comment]
`rawShareCount` no longer exists on main but the function that does get estimate txBytes in estimate_square_size does now account for the unit length prefixed to every transaction including malleated transactions.

https://github.com/celestiaorg/celestia-app/blob/1b80b94a62c8c292f569e2fc576e26299985681a/app/estimate_square_size.go#L50-L62

@evan-forbes fixed this seemingly in https://github.com/celestiaorg/celestia-app/commit/12e77d0007666399c8742aac964c9b1551822157
