### ISSUE TITLE
Number of share estimated by `rawShareCount` is inaccurate 

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#14]
For both transactions and evidence, the number of shares is computed by dividing the total amount of bytes to `ContinuationCompactShareContentSize` (see https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/app/estimate_square_size.go#L178). However, `ContinuationCompactShareContentSize` does not account for the first share that has less space for data since it needs to store the `data length (varint 1 to 10 bytes)` (cf. https://github.com/celestiaorg/celestia-app/blob/main/docs/architecture/adr-007-universal-share-prefix.md#proposal). 

**Suggestion:**
- add `shares.DelimLen(txBytes)` to `txBytes` before computing the number of shares; similarly for `evdBytes`. Note that the same solution is used for message shares, i.e., https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/pkg/shares/utils.go#L22.

**Comment by rootulp** [comment]
Agreed with the issue that was identified. We've subsequently changed a few things:
1. the data length (now called sequence length) is a fixed 4 bytes
2. share estimation uses helpers that do account for less space in the first share. See https://github.com/rootulp/celestia-app/blob/6d9c3a427f794d602df25ef797831f75882701eb/app/estimate_square_size.go#L49 

so this issue may no longer be necessary
