### ISSUE TITLE
`FitsInSquare` is incorrect for edge case 

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#16]
In a scenario with 0 messages, 4 shares for transactions and 1 share for evidence, `FitsInSquare` will return `true` for `squareSize=2`. This is because `5/2 <= 2` is true (see https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/pkg/shares/non_interactive_defaults.go#L10). 

**Suggestion:**
```golang
	if len(msgShareLens) == 0 && cursor <= squareSize*squareSize {
		return true, 0
	}
```

**Comment by mpoke** [comment]
Also, shouldn't `FitsInSquare` in a scenario with 0 messages and the transactions and evidence not fitting in the square? i.e., 
```golang
       if len(msgShareLens) == 0 {
              if cursor <= squareSize*squareSize {
                     return true, 0
              } else {
                     return false, 0
              }
       }
```

**Comment by mpoke** [comment]
The issue can be reproduced by adding the following UT to [TestFitsInSquare](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/pkg/shares/non_interactive_defaults_test.go#L47)
```golang
		{
			name:  "0 msgs (0 msg shares, 5 compact, size 2)",
			msgs:  []int{},
			start: 5,
			size:  2,
			fits:  false,
		},
```

**Comment by rootulp** [comment]
Great find, thanks for sharing and including the unit test case!
