### ISSUE TITLE
Celestia App ADR006: `roundUpBy` function can be "simplified"

### ISSUE THREAD

**Issue by sergio-mena** [informalsystems/audit-celestia#19]
Function `roundUpBy`, can be made more efficient by using known methods of "getting next multiple".

For instance, with the following hunk, the unit tests inside `pkg/shares` are still passing:

```diff
diff --git a/pkg/shares/non_interactive_defaults.go b/pkg/shares/non_interactive_defaults.go
--- a/pkg/shares/non_interactive_defaults.go
+++ b/pkg/shares/non_interactive_defaults.go
@@ -67,14 +67,7 @@ func NextAlignedPowerOfTwo(cursor, msgLen, squareSize int) (int, bool) {
 // roundUpBy rounds cursor up to the next multiple of v. If cursor is divisible
 // by v, then it returns cursor
 func roundUpBy(cursor, v int) int {
-       switch {
-       case cursor == 0:
-               return cursor
-       case cursor%v == 0:
-               return cursor
-       default:
-               return ((cursor / v) + 1) * v
-       }
+       return ((cursor + v - 1) & (-v))
 }
 
 func nextPowerOfTwo(v int) int {
```

Caveat: there is an obvious tradeoff here between readability and efficiency.

**Comment by rootulp** [comment]
Thanks for sharing this optimization! I benchmarked the new implementation in this [commit](https://github.com/celestiaorg/celestia-app/commit/f9c1d0a3bb5286d2e9fa7d39c3e4eb448648caf0)

```
$ go test -bench=.

goos: darwin
goarch: arm64
pkg: github.com/celestiaorg/celestia-app/pkg/shares
Benchmark_roundUpBy4-10         1000000000               0.3107 ns/op
Benchmark_roundUpBy8-10         1000000000               0.3106 ns/op
Benchmark_roundUpBy16-10        1000000000               0.3150 ns/op
Benchmark_roundUpByNew4-10      1000000000               0.3110 ns/op
Benchmark_roundUpByNew8-10      1000000000               0.3110 ns/op
Benchmark_roundUpByNew16-10     1000000000               0.3115 ns/op
PASS
ok      github.com/celestiaorg/celestia-app/pkg/shares  3.711s
```

It looks like the new implementation is faster for large cursors (i.e `cursor=16`) but slower for small cursors (i.e. `cursor=4`, `cursor=8`). Given the performance improvement isn't that significant I'm inclined to use whichever implementation is more readable. IMO the current implementation is more readable but that's a subjective argument.

**Comment by sergio-mena** [comment]
Thanks for the data obtained! It was a second thought I had after opening this issue ("don't optimize what doesn't need optimization" :-D).
I think I agree with you: given that the improvement is not that stellar, I'd favor readability.
We can probably close this issue.

**Comment by rootulp** [comment]
We definitely appreciate the optimization ideas so please keep opening issues!
