### ISSUE TITLE
`MsgPayForData.ValidateBasic` doesn't invalidate reserved namespaces

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#2]
[ValidateBasic](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata.go#L39) should reject `MsgPayForData` messages with `MessageNamespaceId` set to one of the reserved namespace IDs (see https://github.com/celestiaorg/celestia-core/blob/60930abb43458e1f8b321d1eb9e5d6b174975e35/pkg/consts/consts.go#L59).

**Suggestion:**

- Use [ValidateMessageNamespaceID](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/wirepayfordata.go#L125) function.

**Comment by adlerjohn** [comment]
Resolved by https://github.com/celestiaorg/celestia-app/pull/643
