### ISSUE TITLE
`x/payment/payfordata.go` only used for testing

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#3]
The code in `x/payment/payfordata.go` is only used for testing.

**Suggestion:**
- move to a `_test.go` file to increase code readability

**Comment by evan-forbes** [comment]
This is actually our canonical API for submitting a payment tx, and moving this would make it not accessible to [celestia-node](https://github.com/celestiaorg/celestia-node/blob/ac4324ccbbf4bcae5da64bf9dbfc9ef459d9fb10/service/state/core_access.go#L117-L124). imo I think it makes sense to keep it where it is, but perhaps we could consider putting it somewhere else assuming celestia-node is also onboard.

**Comment by rootulp** [comment]
This seems safe to close as not planned. Please re-open if either of you feel differently.
