### ISSUE TITLE
Celestia-Core: Why evidence is part of the `Data` struct

### ISSUE THREAD

**Issue by sergio-mena** [informalsystems/audit-celestia#37]
During our meeting today (2022-12-16), @evan-forbes and @rootulp pointed out right away that this subject is not new and that some discussions took place during Celestia's last retreat.

In an attempt not to re-open settled discussions, I will not start a dissertation here on what the best approach is. I will just report on the following thought (which I shared in the meeting) in case you think it could/should be taken into account:

* Messages are bulky by their very nature. This bulkiness is what motivates the sampling of light clients in the first place, so they don't need to download GiBs and GiBs to ensure the block's data is available.
* Evidence is supposed to be very scarce (if you have a volume of evidence comparable to that of messages, you are in deep trouble!), so why bother sampling it? If light clients deem evidence important (like, e.g. the info in `LastCommit`) then they can just check if it can be downloaded.

**Comment by rootulp** [comment]
This discussed partially served as motivation for moving evidence from the `Data` struct back to the Tendermint `Block`. See https://github.com/celestiaorg/celestia-app/issues/950

**Comment by sergio-mena** [comment]
Thanks @rootulp for the update!
