### ISSUE TITLE
Comment of `NextHighestPowerOf2` is inaccurate

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#4]
The comment of the [NextHighestPowerOf2](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata.go#L192) function is inaccurate, i.e., 
```
// NextHighestPowerOf2 returns the next lowest power of 2 unless the input is a power
// of two, in which case it returns the input
```
while `NextHighestPowerOf2` returns the next power of two if the input is a power of two, i.e.,
```
	// force the value to the next highest power of two if its the same
	if v == i {
		return 2 * v
	}
```
This is also observable in the `TestNextHighestPowerOf2` [testing function](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata_test.go#L83).

**Comment by rootulp** [comment]
Resolved by https://github.com/celestiaorg/celestia-app/pull/644

**Comment by rootulp** [comment]
I don't have permission to close issues in this repo. @mpoke is it possible to grant me permission?

**Comment by rootulp** [comment]
Thanks Marius for granting me permission!
