### ISSUE TITLE
Description of index and leaf hash in absence proof

### ISSUE THREAD

**Issue by andrijamitrovic23** [informalsystems/audit-celestia#40]
@staheri14 Through [this commit](https://github.com/celestiaorg/nmt/commit/4276d172f18c87ebdd18da0cc4b758f0dd164118), descriptions about index and leaf hash in case of absence proof are changed in two places ([first](https://github.com/celestiaorg/nmt/commit/4276d172f18c87ebdd18da0cc4b758f0dd164118) and [second](https://github.com/celestiaorg/nmt/commit/4276d172f18c87ebdd18da0cc4b758f0dd164118) place) to be aligned with the [documentation](https://github.com/celestiaorg/nmt/blob/4276d172f18c87ebdd18da0cc4b758f0dd164118/spec/nmt.md#L88).

But there is a [third description](https://github.com/celestiaorg/nmt/blob/4276d172f18c87ebdd18da0cc4b758f0dd164118/nmt.go#L335-L338) above the `calculateAbsenceIndex` function that needs to be changed too.

**Comment by staheri14** [comment]
Thanks @andrijamitrovic23 for bringing this to our attention! please see the fix in the following PR https://github.com/celestiaorg/nmt/pull/119/files

**Comment by staheri14** [comment]
@andrijamitrovic23 Since the issue has been resolved, I think it makes sense for it to be closed, WDYT?

**Comment by andrijamitrovic23** [comment]
@staheri14 Yes, you can close it.

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/nmt/pull/119
