### ISSUE TITLE
Typo at the nmt documentation

### ISSUE THREAD

**Issue by andrijamitrovic23** [informalsystems/audit-celestia#41]
This is a minor issue. There is a typo at the nmt documentation .  

The typo is located in the section "NMT Data Structure"  under the rule for calculating hash for "Non-leaf Nodes". At the very beginning when children of an intermediary node `n` are presented the characters `r` and `l` should be switched.

**Comment by staheri14** [comment]
Thanks for reporting the issue, it is addressed in the following PR https://github.com/celestiaorg/nmt/pull/120.

**Comment by staheri14** [comment]
Given that the issue is being addressed, what do you think about closing it? @andrijamitrovic23
