### ISSUE TITLE
`CreateCommitment` could be expensive for `CheckTx`

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#6]
Cf. https://docs.cosmos.network/v0.45/basics/tx-lifecycle.html#guideline 
> Gas is not charged when ValidateBasic is executed

This means that an attacker could DOS the system by sending invalid `MsgWirePayForData`s (that fail the check [here](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/wirepayfordata.go#L116)). The `ValidateBasic` of each `msg` of type `MsgWirePayForData` contains a call to `CreateCommitment` for every commit in `msg.MessageShareCommitment`. Every call to `CreateCommitment` entails computing multiple hashes (see [here](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata.go#L125)).

**Comment by musalbas** [comment]
Can this be fixed by somehow rate limiting transactions by IP or blacklisting IPs that repeatedly send invalid transactions?

**Comment by mpoke** [comment]
A few comments regarding https://github.com/celestiaorg/celestia-app/pull/666
- `ValidateAllSquareSizesCommitedTo` is invoked after invoking `CreateCommitment` for each `MessageShareCommitment`. IMO, `ValidateAllSquareSizesCommitedTo` is the cheaper check.
- The check on this [line](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/wirepayfordata.go#L148) is redundant as it's done [here](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/wirepayfordata.go#L160).
- IIUC from `ValidateAllSquareSizesCommitedTo`, the expectation is that the users have access to both `MinSquareSize` and `MaxSquareSize`, and they MUST submit `MsgWirePayForData` with a `MessageShareCommitment` for each [possible square size](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/square_sizes.go#L15). Is that right?

**Comment by adlerjohn** [comment]
> the expectation is that the users have access to both MinSquareSize and MaxSquareSize, and they MUST submit MsgWirePayForData with a MessageShareCommitment for each [possible square size](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/square_sizes.go#L15). Is that right?

If by "possible" you mean that the data will fit in the square, then yes. This means square sizes that are too small or too large aren't included.

**Comment by mpoke** [comment]
It also means that `MsgWirePayForData` transactions that don't have `MessageShareCommitment`s for all possible square sizes (i.e., 1, 2, 4, 8, 16, 32, 64, and 128) will be rejected. Right?

**Comment by adlerjohn** [comment]
No, it will only be rejected if it doesn't have all valid and non-redundant square sizes. If a data blob is 16 shares, then only commitments for sizes`[4, 8, 16]` are needed.

**Comment by mpoke** [comment]
IIUC, for a message that fits in 16 shares (i.e., ` MsgSharesUsed(msgSize int)` returns 16), the [AllSquareSizes](https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/square_sizes.go#L27) method returns `[8, 16, 32, 64, 128]`. This must match the `SquareSize` of the `MessageShareCommitment`s (cf. https://github.com/celestiaorg/celestia-app/blob/e088d61fcb6579b4bc797deefd2ceff7601aa079/x/payment/types/wirepayfordata.go#L152).

**Comment by adlerjohn** [comment]
Then that's either a bug in `AllSquareSizes`, or a bug in how it's used. If a data blob fits on a single row, then all greater square sizes would have the same commitment and so aren't needed.

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/236 which hasn't been implemented yet

**Comment by rootulp** [comment]
I think this attack is significantly less expensive after the adoption of [square size independent message commitments](https://github.com/celestiaorg/celestia-app/blob/58352d17a16910ca7de94279b7a25c1ac5b0d791/docs/architecture/adr-008-square-size-independent-message-commitments.md) because validating a `MsgWirePayForBlob` now only includes one [`CreateCommitment` invocation](https://github.com/celestiaorg/celestia-app/blob/58352d17a16910ca7de94279b7a25c1ac5b0d791/x/blob/types/wirepayforblob.go#L108). 

Is it safe to close this issue?
