### ISSUE TITLE
`WirePayForData` with empty `Message` 

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#8]
`MsgWirePayForData.ValidateBasic` doesn't check if `msg.MessageSize == 0`. As a result, a malicious user could spam the system with `WirePayForData` transactions with no data. Such attack is possible since the gas consumed per TXs is `msg.MessageSize` (there are no reads or writes to the store). 

 **Suggestions:**

- Add checks to invalidated `WirePayForData` transactions with `MessageSize == 0`
- Add to the amount of gas consumed a constant that doesn't depend on the `MessageSize`

**Comment by evan-forbes** [comment]
Great find! We definitely have to address the spamming issue, so I don't want to distract from that, but just to note that there is currently a very small base fee added by the default cosmos-sdk for all txs for signature verification and size of tx.

https://github.com/cosmos/cosmos-sdk/blob/fc7ee0bf1e4e6afef4aed98515d418281edb7e62/x/auth/ante/ante.go#L44

https://github.com/cosmos/cosmos-sdk/blob/fc7ee0bf1e4e6afef4aed98515d418281edb7e62/x/auth/ante/ante.go#L48

this is something that we have to consider when designing a goal base fee and proper resource allocation, which we still need to do a lot of work for https://github.com/celestiaorg/celestia-app/issues/658

**Comment by mpoke** [comment]
>  there is currently a very small base fee added by the default cosmos-sdk for all txs for signature verification and size of tx.
> 
> https://github.com/cosmos/cosmos-sdk/blob/fc7ee0bf1e4e6afef4aed98515d418281edb7e62/x/auth/ante/ante.go#L44
> 
> https://github.com/cosmos/cosmos-sdk/blob/fc7ee0bf1e4e6afef4aed98515d418281edb7e62/x/auth/ante/ante.go#L48

Thanks. I was not aware of it, but I was hoping that something like this exists  :)

**Comment by rootulp** [comment]
> Add to the amount of gas consumed a constant that doesn't depend on the `MessageSize`

No longer seems necessary given the above

> Add checks to invalidated WirePayForData transactions with MessageSize == 0

Added in https://github.com/celestiaorg/celestia-app/pull/1083
